# Generated by Django 6.0.2 on 2026-02-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='အမည်')),
                ('email', models.EmailField(max_length=254, verbose_name='အီးမေးလ်')),
                ('subject', models.CharField(max_length=255, verbose_name='ခေါင်းစဉ်')),
                ('message', models.TextField(verbose_name='မက်ဆေ့ခ်ျ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_replied', models.BooleanField(default=False, verbose_name='ပြန်လည်ဖြေကြားပြီး')),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
