# Generated by Django 6.0.2 on 2026-02-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Project အမည်')),
                ('category', models.CharField(choices=[('Web', 'Web Development'), ('Mobile', 'Mobile App'), ('System', 'System / Software'), ('Design', 'UI/UX Design')], max_length=50, verbose_name='အမျိုးအစား')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Project ပုံ')),
                ('description', models.TextField(verbose_name='အကြောင်းအရာအသေးစိတ်')),
                ('tech_stack', models.CharField(max_length=255, verbose_name='အသုံးပြုထားသော နည်းပညာများ')),
                ('live_link', models.URLField(blank=True, null=True, verbose_name='Live URL')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='အမည်')),
                ('role', models.CharField(max_length=100, verbose_name='ရာထူး')),
                ('image', models.ImageField(upload_to='team/', verbose_name='ပရိုဖိုင်ပုံ')),
                ('bio', models.TextField(verbose_name='ကိုယ်ရေးအကျဉ်း')),
                ('skills', models.CharField(max_length=255, verbose_name='ကျွမ်းကျင်သော နည်းပညာများ')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
