# Generated by Django 6.0.2 on 2026-02-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ခေါင်းစဉ်')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(upload_to='blog_thumbnails/', verbose_name='မျက်နှာဖုံးပုံ')),
                ('content', models.TextField(verbose_name='ဆောင်းပါးအကြောင်းအရာ')),
                ('excerpt', models.CharField(help_text='စာမျက်နှာအပြင်ဘက်တွင် ပြသရန် အကျဉ်းချုပ်', max_length=500, verbose_name='အနှစ်ချုပ်')),
                ('tags', models.CharField(blank=True, help_text='Comma ခံပြီးရေးရန် (ဥပမာ- react, python, django)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='ချက်ချင်းတင်မည်')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ရေးသားသူ')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
