# Generated by Django 5.2.8 on 2026-05-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCTASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Build Something Great?', max_length=255)),
                ('description', models.CharField(default='Get 20% (up to $100) off your first payment for a limited time!', max_length=500)),
                ('button1_text', models.CharField(default='Start Your Project', max_length=100)),
                ('button1_link', models.CharField(default='/contact', max_length=255)),
                ('button2_text', models.CharField(default='Explore Services', max_length=100)),
                ('button2_link', models.CharField(default='/services', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeExploreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon_name', models.CharField(default='Sparkles', max_length=50)),
                ('link', models.CharField(blank=True, default='/', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='We design first', max_length=100)),
                ('title_prefix', models.CharField(default='lwal', max_length=100)),
                ('title_highlight', models.CharField(default='kuu', max_length=100)),
                ('subtitle', models.CharField(default='from generative models to agentic automation', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='home/images/')),
                ('section', models.CharField(default='hero', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='Globe', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/services/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('suffix', models.CharField(default='k', max_length=10)),
                ('icon_name', models.CharField(default='TrendingUp', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
