# Generated by Django 5.2.8 on 2026-06-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
